velodrome plugin
goat-sdk/goat pull request #112
Opened 2024-12-20 06:24 UTC by kamalbuilds

# Velodrome Plugin for Goat SDK

## Background

This PR adds support for Velodrome Finance, a leading AMM on Optimism, to the Goat SDK. The plugin enables AI agents to interact with Velodrome's core features including token swaps and liquidity provision.

The plugin uses the official Velodrome V2 contracts and follows the same patterns as other successful Goat SDK plugins like Kim and Polymarket. It's designed to be easy to use while providing comprehensive safety features for AI agents interacting with Velodrome.

## What does this PR do?

Adds a new plugin (@goat-sdk/plugin-velodrome) that implements:

1. Token Swaps
   - Direct token-to-token swaps
   - Support for both stable and volatile pools
   - Slippage protection via amountOutMin parameter

2. Liquidity Provision
   - Add liquidity to stable/volatile pools
   - Support for minimum amounts to prevent sandwich attacks
   - Optional recipient address for LP tokens

Key features:
- Full TypeScript support with comprehensive type definitions
- Parameter validation using Zod schemas
- Chain validation (Optimism only)
- Proper error handling
- Support for both standard and hosted wallets

## What kind of change is this?

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Documentation changes needed?

Yes, documentation should be updated to include:
- Installation and setup instructions
- Examples for swapping tokens
- Examples for providing liquidity
- Parameter descriptions and types
- Supported chains (Optimism)

## Testing

### Detailed testing steps

1. Token Swaps
```typescript
const plugin = velodrome();
await agent.use(plugin).execute("swap_exact_tokens", {
    tokenIn: "0x...", // USDC
    tokenOut: "0x...", // WETH
    amountIn: "500",
    amountOutMin: "0.25",
    tokenInDecimals: 6,
    tokenOutDecimals: 18
});
```

2. Add Liquidity
```typescript
await agent.use(plugin).execute("add_liquidity", {
    token0: "0x...", // USDC
    token1: "0x...", // WETH
    stable: false,
    amount0Desired: "1000",
    amount1Desired: "0.5",
    amount0Min: "995",
    amount1Min: "0.495",
    token0Decimals: 6,
    token1Decimals: 18
});
```

### Plugin Testing Checklist
- [x] Tested with key pair wallets
- [x] Tested with hosted wallets
- [x] Verified transaction success on Optimism
- [x] Verified proper error handling
- [x] Verified slippage protection works
- [x] Verified deadline handling works

## Discord username
0xkamal7

2024-12-20 06:27 UTC, kamalbuilds commented
Note: This is a WIP rn and I am testing the plugin on some chains like mode

2024-12-23 10:10 UTC, 0xaguspunk requested changes
Neat!! 🔥 Made a few comments!

Missing:
* Screenshot of the tools working!

2024-12-23 10:10 UTC, 0xaguspunk commented on typescript/examples/vercel-ai/velodrome/README.md
> +# Vercel AI with viem Example
Why are we pushing this example? Does not include the velodrome plugin. I would remove this whole package, not needed

2024-12-23 10:10 UTC, 0xaguspunk commented on typescript/packages/plugins/velodrome-plugin/src/parameters.ts
> +        amountIn: z.string().describe("The amount of input tokens to swap"),
I would specify that all amounts are base units

2024-12-23 10:10 UTC, 0xaguspunk commented on typescript/packages/plugins/velodrome-plugin/src/velodrome.service.ts
> +        const amountIn = parseUnits(parameters.amountIn, parameters.tokenInDecimals);
Would not parse these here, let the LLM figure out when to use the convertToBaseUnits tool :)

2024-12-23 10:10 UTC, 0xaguspunk commented on typescript/packages/plugins/velodrome-plugin/src/velodrome.service.ts
> +        const deadline = Math.floor(Date.now() / 1000) + 60 * 20; // 20 minutes
Ok to have a default! To parametrize it tho I would follow what we have in the kim protocol plugin :)

* https://github.com/goat-sdk/goat/blob/main/typescript/packages/plugins/kim/src/parameters.ts#L38
* https://github.com/goat-sdk/goat/blob/main/typescript/packages/plugins/kim/src/kim.service.ts#L48

2025-01-09 15:07 UTC, kamalbuilds commented on typescript/examples/vercel-ai/velodrome/CHANGELOG.md
> +# goat-examples-vercel-ai-viem
removed

2025-01-09 18:46 UTC, kamalbuilds commented on typescript/packages/plugins/velodrome-plugin/src/parameters.ts
> +        amountIn: z.string().describe("The amount of input tokens to swap"),
done

2025-01-18 02:29 UTC, kamalbuilds commented
@0xaguspunk Working screenshot 

<img width="955" alt="Screenshot 2025-01-18 at 7 59 28 AM" src="https://github.com/user-attachments/assets/3caaa323-4b95-42b8-b0d5-ed52fe333c2b" />

2025-01-18 03:00 UTC, kamalbuilds commented
SS for Adding Liquidity using Valedrome plugin,

<img width="483" alt="image" src="https://github.com/user-attachments/assets/da343a57-fd99-43ec-800a-7d8534d13396" />

2025-01-22 07:51 UTC, 0xaguspunk approved these changes

2025-01-22 07:57 UTC, merged