Zerodev global address plugin
goat-sdk/goat pull request #152
Opened 2024-12-28 19:14 UTC by MahmoudMohajer

# Relates to:

# Background
This plugin enables the goat to create Zerodev global address for given wallet address for the given target chain and you can send supported ERC20, native, and wrapped native coins to the created global address. 

## What does this PR do?
This PR adds the zerodev-global-address plugin to goat sdk and provides a simple example using vercel-ai sdk.

# Testing

## Detailed testing results

| **Method**                                    | **Prompt**                                                                                      | **Screenshot**                                                                                 |
|-----------------------------------------------|------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|
| Create global address from wallet client      | Get wallet address and create global address for optimism                                      | ![image](https://github.com/user-attachments/assets/d43b08fb-dc05-4073-813d-a4e04465d063)      |
| Create a global address for arbitrary wallet address | Create global address for this 0xb2F34eF53b5555E7249C24d17FDb2225B9F5130b on base              | ![image](https://github.com/user-attachments/assets/72840de2-c888-41f0-ab5c-dc4c5cd6f2e1)      |

# Docs

## For plugins
- [x] I have tested this change locally with key pair wallets
- [x] I have tested this change locally with hosted wallets (e.g. Crossmint Smart Wallets, etc.)
- [x] Package exists in the [goat workspace file](https://github.com/goat-sdk/goat/blob/main/goat.code-workspace)

## Discord username
mahmoudmohajer

2024-12-30 12:29 UTC, 0xaguspunk requested changes
Nice! :) Great PR 🔥 Made some comments!

2024-12-30 19:14 UTC, MahmoudMohajer commented
Implemented suggested code refactors.

2024-12-31 11:18 UTC, 0xaguspunk approved these changes

2024-12-31 11:20 UTC, 0xaguspunk commented
Awesome!! 🔥 

You'll need to:
1. Merge main
2. Resolve the conflicts (one is deleting the `pnpm-lock` file and running pnpm install again
3. Fix the lint issues (you can run `pnpm lint:fix`)

2024-12-31 13:34 UTC, MahmoudMohajer commented
@0xaguspunk  applied the required changes.

2025-01-01 12:21 UTC, 0xaguspunk approved these changes

2025-01-01 12:21 UTC, merged

2025-01-02 22:33 UTC, fede2442 commented
Hey @MahmoudMohajer please share an EVM wallet and thanks again for contributing!

2025-01-03 04:14 UTC, MahmoudMohajer commented
thank you for giving me this opportunity @fede2442. 

EVM walllet address: 0x228bB8BcbCEc34e5b2E82791D916E577FC6C6C7a