Chr wallet check
goat-sdk/goat pull request #65
Opened 2024-12-13 07:39 UTC by superoo7

# Relates to:

# Background

## What does this PR do?
- Add wallet check validation to prevent sending to wrong address
![Screenshot 2024-12-13 at 3 39 25 PM](https://github.com/user-attachments/assets/fbce5345-ba1a-4875-8597-0d1add106253)

## What kind of change is this?

# Documentation changes needed?

# Testing

## Detailed testing steps

## For plugins
- [x] I have tested this change locally with key pair wallets
- [x] I have tested this change locally with hosted wallets (e.g. Crossmint Smart Wallets, etc.)

## Discord username

2024-12-13 14:07 UTC, 0xaguspunk requested changes

2024-12-13 14:07 UTC, 0xaguspunk commented on typescript/.changeset/tame-tomatoes-doubt.md
> +"@goat-sdk/wallet-chromia": minor
Seems more like a patch! You can simply update this and change `minor` for `patch`

2024-12-15 10:50 UTC, superoo7 commented
Found an issue on the transaction hash, fixing it btw

2024-12-16 08:49 UTC, 0xaguspunk approved these changes

2024-12-16 08:49 UTC, merged